#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members

};

#endif // __EvtFramePrincipal__
