#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
enum
{
ID_THREAD_ACQUISITION= 201,
ID_THREAD_LECTEUR,
ID_THREAD_IMPRESSION
};
#include <ThreadImpression.h>
#include <Thread_acquisition_CB.h>
#include <Thread_gestion_CB.h>
#include <CommunicationThread.h>
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
    class Thread_acquisition_CB;
    class ThreadLectureCb;
    class ThreadImpression;
	protected:
		// Handlers for FramePrincipal events.
		void OnCloseFrame( wxCloseEvent& event );
		void OnBoutonNonScolaireClick( wxCommandEvent& event );
		void OnBoutonScolaireClick( wxCommandEvent& event );
		void OnBoutonInconnuClick( wxCommandEvent& event );
		void OnBoutonInvalideClick( wxCommandEvent& event );
		void OnBoutonFinClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
    void OnThreadAcqusitionEvent(wxCommandEvent &event);
    void OnThreaImpressionEvent(wxCommandEvent &event);
    void OnthreadLetectureEvent(wxCommandEvent &event);
    
    private:
    CommunicationThread *m_communication;
    bool m_Thread_Acquisition_Fini, m_Thread_Lecteur_Fini, m_ThreadImpressionFini;
    ThreadImpression *m_thread_impression;
    Thread_acquisition_CB * m_thread_acquisition;
    ThreadLectureCb *m_thread_lecteur;
    int m_ValeurTampon;
    
    
};

#endif // __EvtFramePrincipal__
