#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
enum
{
ID_THREAD_CODE_BARRES= 201,
ID_THREAD_CONSOMMATEUR
};

class Thread_code_barres;
class ThreadConsommateur;
#include "CommunicationThread.h"
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnCLoseFrame( wxCloseEvent& event );
		void OnboutonNonScolaireClick( wxCommandEvent& event );
		void OnboutonScolaireClick( wxCommandEvent& event );
		void OnboutonInconnuClick( wxCommandEvent& event );
		void OnBoutonInvalideClick( wxCommandEvent& event );
		void OnBoutonFinClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
    private:
        CommunicationThread *m_communication;
        bool m_ThreadCb_Fini, m_ThreadConsFini;
        Thread_code_barres *m_thread_CB;
        ThreadConsommateur *m_thread_conso;
        void OnThreadCodeBarresEvent(wxCommandEvent& event);
        void OnThreadConsommateurEvent(wxCommandEvent& event);





};

#endif // __EvtFramePrincipal__
