.PHONY: clean All

All:
	@echo "----------Building project:[ Squelette_restauration - Debug ]----------"
	@cd "Squelette_restauration" && "$(MAKE)" -f  "Squelette_restauration.mk"
clean:
	@echo "----------Cleaning project:[ Squelette_restauration - Debug ]----------"
	@cd "Squelette_restauration" && "$(MAKE)" -f  "Squelette_restauration.mk" clean
