.PHONY: clean All

All:
	@echo "----------Building project:[ Squelette-Resauration - Release ]----------"
	@cd "Squelette-Resauration" && "$(MAKE)" -f  "Squelette-Resauration.mk"
clean:
	@echo "----------Cleaning project:[ Squelette-Resauration - Release ]----------"
	@cd "Squelette-Resauration" && "$(MAKE)" -f  "Squelette-Resauration.mk" clean
